---
# System configuration
haproxy_firewalld: false # firewalld not installed in image

# Configuration
## Global Configuration
haproxy_global_logs:
  - "127.0.0.1 local2"
haproxy_global_tunes: []
## Default Configuration
haproxy_default_mode: http
haproxy_default_options:
  - dontlognull
  - http-server-close
  - redispatch
## Stats Configuration
haproxy_stats_auth: false
## Listen Configuration
haproxy_listen:
  - api-server-6443:
      binds:
        - "*:6443"
      mode: "tcp"
      servers:
        - "bootstrap 10.0.0.11:6443 check inter 1s backup"
        - "master01 10.0.0.21:6443 check inter 1s"
        - "master02 10.0.0.22:6443 check inter 1s"
        - "master03 10.0.0.23:6443 check inter 1s"
  - machine-config-server-22623:
      binds:
        - "*:22623"
      mode: "tcp"
      servers:
        - "bootstrap 10.0.0.11:22623 check inter 1s backup"
        - "master01 10.0.0.21:22623 check inter 1s"
        - "master02 10.0.0.22:22623 check inter 1s"
        - "master03 10.0.0.23:22623 check inter 1s"
  - ingress-router-443:
      binds:
        - "*:443"
      mode: "tcp"
      balance: "source"
      servers:
        - "worker01 10.0.0.31:443 check inter 1s"
        - "worker02 10.0.0.32:443 check inter 1s"
  - ingress-router-80:
      binds:
        - "*:80"
      mode: "tcp"
      balance: "source"
      servers:
        - "worker01 10.0.0.31:80 check inter 1s"
        - "worker02 10.0.0.32:80 check inter 1s"
