---
nginx_start: false
nginx_selinux: true
nginx_selinux_tcp_ports: 8080

nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    backup: true
    config:
      servers:
        - core:
            listen:
              - port: 8080
            root: "/usr/share/nginx"
          locations:
            - location: /
          autoindex:
            enable: true
