---
# roles:
#   - name: example.role
#     version: 1.0.0

collections:
  - name: community.general
    version: 8.1.0
  - name: ansible.posix
    version: 1.5.4
  - name: mwadman.networkmanager_roles
    version: 1.0.1
  - name: mwadman.dnsmasq_roles
    version: 1.0.0

roles:
  - name: uoi-io.haproxy
    version: v1.5.7
  - name: nginxinc.nginx
    version: 0.24.1
  - name: nginxinc.nginx_config
    version: 0.7.0
