---
- name: Download OpenShift Mirror Registry Tool
  ansible.builtin.get_url:
    url: "https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/\
          {{ mirror_registry_version }}/mirror-registry.tar.gz"
    checksum: "sha256:https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/\
               {{ mirror_registry_version }}/mirror-registry.tar.gz.sha256"
    dest: "/root/mirror-registry.tar.gz"
    mode: "644"

- name: Extract OpenShift Mirror Registry Tool
  ansible.builtin.unarchive:
    src: "/root/mirror-registry.tar.gz"
    remote_src: true
    dest: "/root/"
    creates: "/root/mirror-registry"

- name: Create directories required for registry
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - path: "/srv/quayRoot"
      mode: "0700"
    - path: "/srv/quayStorage"
      mode: "0730"

- name: Install Mirror Registry
  ansible.builtin.command:
    cmd: "/root/mirror-registry install
          --initUser init --initPassword MirrorRegistry
          --quayHostname mirrorregistry.none.vagrant --quayRoot /srv/quayRoot --quayStorage /srv/quayStorage"
    creates: "/etc/systemd/system/quay-pod.service"
  register: "registry_install"
  changed_when: registry_install.stdout != "skipped, since /etc/systemd/system/quay-pod.service exists"
