---
- name: Create local directories for Openshift installation
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "directory"
    mode: "0755"
  loop:
    - path: "../openshift/tools"
    - path: "../openshift/install"
    - path: "../openshift/images"

- name: Download Openshift Install Tools
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ install_client_version }}/openshift-install-linux-{{ install_client_version }}.tar.gz"
      dest: "../openshift/tools/openshift-install-linux.tar.gz"
      checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ install_client_version }}/sha256sum.txt"
      mode: "644"
    - url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ install_client_version }}/openshift-client-linux-{{ install_client_version }}.tar.gz"
      dest: "../openshift/tools/openshift-client-linux.tar.gz"
      checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ install_client_version }}/sha256sum.txt"
      mode: "644"
    - url: "https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane"
      dest: "../openshift/tools/butane"
      checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/sha256sum.txt"
      mode: "755"
    - url: "https://mirror.openshift.com/pub/openshift-v4/clients/coreos-installer/latest/coreos-installer"
      dest: "../openshift/tools/coreos-installer"
      checksum: "sha256:https://mirror.openshift.com/pub/openshift-v4/clients/coreos-installer/latest/sha256sum.txt"
      mode: "755"

- name: Extract Openshift Install Tools
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "../openshift/tools/"
    creates: "{{ item.creates }}"
  loop:
    - src: "../openshift/tools/openshift-install-linux.tar.gz"
      creates: "../openshift/tools/openshift-install"
    - src: "../openshift/tools/openshift-client-linux.tar.gz"
      creates: "../openshift/tools/oc"

- name: Import Configuration Generation Tasks
  ansible.builtin.import_tasks:
    file: "generate.yml"

- name: Import Image Download Tasks
  ansible.builtin.import_tasks:
    file: "images.yml"
