---
mirror_openshift_version: "4.14"

mirror_registry_version: "1.3.9"
mirror_client_version: "4.14.11"

mirror_imageset_channels:
  - name: "stable-{{ mirror_openshift_version }}"
    type: "ocp"
mirror_imageset_catalogs: [] # Will retrieve no catalogs
# Can determine catalogs available for a version by running `oc-mirror list operators --catalogs --version 4.14`
# Can determine operators available in catalog by running `oc-mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.14`
# To retrieve all operators in a catalog
# mirror_imageset_catalogs:
#   - name: "registry.redhat.io/redhat/redhat-operator-index:v{{ mirror_openshift_version }}"
#     operators: []
# To retrieve some operators in a catalog
# mirror_imageset_catalogs:
#   - name: "registry.redhat.io/redhat/redhat-operator-index:v{{ mirror_openshift_version }}"
#     operators:
#       - name: "web-terminal"
#         channels:
#           - "fast"
mirror_imageset_images:
  - "registry.redhat.io/ubi9/ubi:latest"
