---
- name: Configure networks via nmcli
  hosts: mirrorregistry
  become: true
  roles:
    - mwadman.networkmanager_roles.nmcli

- name: Re-run gather_facts after network interface update
  hosts: mirrorregistry
  become: true
  tasks:
    - name: Re-run gather_facts
      ansible.builtin.gather_facts:
        parallel: true

- name: Resize filesystem to full disk size
  hosts: mirrorregistry
  become: true
  handlers:
    - name: Resize filesystem
      ansible.builtin.command:
        cmd: "xfs_growfs /"
      register: xfs_growfs_command
      changed_when: "'data blocks changed' in xfs_growfs_command.stdout"
  tasks:
    - name: Install growpart utility
      ansible.builtin.package:
        name: "cloud-utils-growpart"
        state: "present"
    - name: Resize Partition
      ansible.builtin.command:
        cmd: "growpart
              {{ (ansible_mounts | selectattr('mount', 'eq', '/') | map(attribute='device') | first)[:-1] }}
              {{ (ansible_mounts | selectattr('mount', 'eq', '/') | map(attribute='device') | first)[-1:] }}" # e.g. "growpart /dev/vda 5"
      register: growpart_command
      changed_when: "'CHANGED' in growpart_command.stdout"
      failed_when:
        - "'NOCHANGE' not in growpart_command.stdout"
        - "growpart_command.rc != 0"
      notify: "Resize filesystem"

- name: Set Up Mirror Registry
  hosts: mirrorregistry
  become: true
  roles:
    - mirror_registry
    - mwadman.dnsmasq_roles.dnsmasq
    - uoi-io.haproxy
    - nginxinc.nginx
    - nginxinc.nginx_config

- name: Create OpenShift configurations
  hosts: localhost
  become: false
  roles:
    - openshift_config
